/*
 * IdentityExpress Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nanthealth.identityexpress.api.client.test;

import org.junit.Test;

import com.nanthealth.identityexpress.api.client.ApiException;
import com.nanthealth.identityexpress.api.client.api.ClaimTypesApi;
import com.nanthealth.identityexpress.api.client.model.ClaimTypeDto;
import com.nanthealth.identityexpress.api.client.model.CreateClaimTypeDto;

import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClaimTypesApi
 */
@Ignore
public class ClaimTypesApiTest {

    private final ClaimTypesApi api = new ClaimTypesApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void claimTypesByIdDeleteTest() throws ApiException {
        String id = null;
        api.claimTypesByIdDelete(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void claimTypesByIdGetTest() throws ApiException {
        String id = null;
        api.claimTypesByIdGet(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void claimTypesByIdPutTest() throws ApiException {
        String id = null;
        ClaimTypeDto claimType = null;
        api.claimTypesByIdPut(id, claimType);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void claimTypesGetTest() throws ApiException {
        String name = null;
        String sort = null;
        api.claimTypesGet(name, sort);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void claimTypesPostTest() throws ApiException {
        CreateClaimTypeDto claimType = null;
        api.claimTypesPost(claimType);

        // TODO: test validations
    }
    
}
