/*
 * IdentityExpress Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nanthealth.identityexpress.api.client.test;

import org.junit.Test;

import com.nanthealth.identityexpress.api.client.ApiException;
import com.nanthealth.identityexpress.api.client.api.IdentityResourcesApi;
import com.nanthealth.identityexpress.api.client.model.CreateIdentityResourceDto;
import com.nanthealth.identityexpress.api.client.model.IdentityResourceDto;

import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IdentityResourcesApi
 */
@Ignore
public class IdentityResourcesApiTest {

    private final IdentityResourcesApi api = new IdentityResourcesApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void identityResourcesByIdDeleteTest() throws ApiException {
        String id = null;
        api.identityResourcesByIdDelete(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void identityResourcesByIdGetTest() throws ApiException {
        String id = null;
        api.identityResourcesByIdGet(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void identityResourcesByIdPutTest() throws ApiException {
        String id = null;
        IdentityResourceDto resource = null;
        api.identityResourcesByIdPut(id, resource);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void identityResourcesGetTest() throws ApiException {
        String name = null;
        api.identityResourcesGet(name);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void identityResourcesPostTest() throws ApiException {
        CreateIdentityResourceDto resource = null;
        api.identityResourcesPost(resource);

        // TODO: test validations
    }
    
}
