/*
 * IdentityExpress Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nanthealth.identityexpress.api.client.test;

import org.junit.Test;

import com.nanthealth.identityexpress.api.client.ApiException;
import com.nanthealth.identityexpress.api.client.api.RolesApi;
import com.nanthealth.identityexpress.api.client.model.CreateRoleDto;
import com.nanthealth.identityexpress.api.client.model.RoleDto;
import com.nanthealth.identityexpress.api.client.model.UserDto;

import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RolesApi
 */
@Ignore
public class RolesApiTest {

    private final RolesApi api = new RolesApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rolesByIdDeleteTest() throws ApiException {
        String id = null;
        api.rolesByIdDelete(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rolesByIdGetTest() throws ApiException {
        String id = null;
        api.rolesByIdGet(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rolesByIdPutTest() throws ApiException {
        String id = null;
        RoleDto role = null;
        api.rolesByIdPut(id, role);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rolesByIdUsersDeleteTest() throws ApiException {
        String id = null;
        List<UserDto> users = null;
        api.rolesByIdUsersDelete(id, users);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rolesByIdUsersPostTest() throws ApiException {
        String id = null;
        List<UserDto> users = null;
        api.rolesByIdUsersPost(id, users);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rolesGetTest() throws ApiException {
        String name = null;
        String sort = null;
        String fields = null;
        api.rolesGet(name, sort, fields);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rolesPostTest() throws ApiException {
        CreateRoleDto role = null;
        api.rolesPost(role);

        // TODO: test validations
    }
    
}
