/*
 * IdentityExpress Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nanthealth.identityexpress.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CreateClaimTypeDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-24T03:48:05.487Z")
public class CreateClaimTypeDto {
  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("required")
  private Boolean required = null;

  @SerializedName("valueType")
  private String valueType = null;

  @SerializedName("rule")
  private String rule = null;

  @SerializedName("ruleValidationFailureDescription")
  private String ruleValidationFailureDescription = null;

  @SerializedName("userEditable")
  private Boolean userEditable = null;

  public CreateClaimTypeDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateClaimTypeDto description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CreateClaimTypeDto required(Boolean required) {
    this.required = required;
    return this;
  }

   /**
   * Get required
   * @return required
  **/
  @ApiModelProperty(value = "")
  public Boolean isRequired() {
    return required;
  }

  public void setRequired(Boolean required) {
    this.required = required;
  }

  public CreateClaimTypeDto valueType(String valueType) {
    this.valueType = valueType;
    return this;
  }

   /**
   * Get valueType
   * @return valueType
  **/
  @ApiModelProperty(value = "")
  public String getValueType() {
    return valueType;
  }

  public void setValueType(String valueType) {
    this.valueType = valueType;
  }

  public CreateClaimTypeDto rule(String rule) {
    this.rule = rule;
    return this;
  }

   /**
   * Get rule
   * @return rule
  **/
  @ApiModelProperty(value = "")
  public String getRule() {
    return rule;
  }

  public void setRule(String rule) {
    this.rule = rule;
  }

  public CreateClaimTypeDto ruleValidationFailureDescription(String ruleValidationFailureDescription) {
    this.ruleValidationFailureDescription = ruleValidationFailureDescription;
    return this;
  }

   /**
   * Get ruleValidationFailureDescription
   * @return ruleValidationFailureDescription
  **/
  @ApiModelProperty(value = "")
  public String getRuleValidationFailureDescription() {
    return ruleValidationFailureDescription;
  }

  public void setRuleValidationFailureDescription(String ruleValidationFailureDescription) {
    this.ruleValidationFailureDescription = ruleValidationFailureDescription;
  }

  public CreateClaimTypeDto userEditable(Boolean userEditable) {
    this.userEditable = userEditable;
    return this;
  }

   /**
   * Get userEditable
   * @return userEditable
  **/
  @ApiModelProperty(value = "")
  public Boolean isUserEditable() {
    return userEditable;
  }

  public void setUserEditable(Boolean userEditable) {
    this.userEditable = userEditable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateClaimTypeDto createClaimTypeDto = (CreateClaimTypeDto) o;
    return Objects.equals(this.name, createClaimTypeDto.name) &&
        Objects.equals(this.description, createClaimTypeDto.description) &&
        Objects.equals(this.required, createClaimTypeDto.required) &&
        Objects.equals(this.valueType, createClaimTypeDto.valueType) &&
        Objects.equals(this.rule, createClaimTypeDto.rule) &&
        Objects.equals(this.ruleValidationFailureDescription, createClaimTypeDto.ruleValidationFailureDescription) &&
        Objects.equals(this.userEditable, createClaimTypeDto.userEditable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, required, valueType, rule, ruleValidationFailureDescription, userEditable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateClaimTypeDto {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("    valueType: ").append(toIndentedString(valueType)).append("\n");
    sb.append("    rule: ").append(toIndentedString(rule)).append("\n");
    sb.append("    ruleValidationFailureDescription: ").append(toIndentedString(ruleValidationFailureDescription)).append("\n");
    sb.append("    userEditable: ").append(toIndentedString(userEditable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

