/*
 * IdentityExpress Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nanthealth.identityexpress.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * EditClaimDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-24T03:48:05.487Z")
public class EditClaimDto {
  @SerializedName("oldClaimType")
  private String oldClaimType = null;

  @SerializedName("oldClaimValue")
  private String oldClaimValue = null;

  @SerializedName("newClaimType")
  private String newClaimType = null;

  @SerializedName("newClaimValue")
  private String newClaimValue = null;

  public EditClaimDto oldClaimType(String oldClaimType) {
    this.oldClaimType = oldClaimType;
    return this;
  }

   /**
   * Get oldClaimType
   * @return oldClaimType
  **/
  @ApiModelProperty(value = "")
  public String getOldClaimType() {
    return oldClaimType;
  }

  public void setOldClaimType(String oldClaimType) {
    this.oldClaimType = oldClaimType;
  }

  public EditClaimDto oldClaimValue(String oldClaimValue) {
    this.oldClaimValue = oldClaimValue;
    return this;
  }

   /**
   * Get oldClaimValue
   * @return oldClaimValue
  **/
  @ApiModelProperty(value = "")
  public String getOldClaimValue() {
    return oldClaimValue;
  }

  public void setOldClaimValue(String oldClaimValue) {
    this.oldClaimValue = oldClaimValue;
  }

  public EditClaimDto newClaimType(String newClaimType) {
    this.newClaimType = newClaimType;
    return this;
  }

   /**
   * Get newClaimType
   * @return newClaimType
  **/
  @ApiModelProperty(value = "")
  public String getNewClaimType() {
    return newClaimType;
  }

  public void setNewClaimType(String newClaimType) {
    this.newClaimType = newClaimType;
  }

  public EditClaimDto newClaimValue(String newClaimValue) {
    this.newClaimValue = newClaimValue;
    return this;
  }

   /**
   * Get newClaimValue
   * @return newClaimValue
  **/
  @ApiModelProperty(value = "")
  public String getNewClaimValue() {
    return newClaimValue;
  }

  public void setNewClaimValue(String newClaimValue) {
    this.newClaimValue = newClaimValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EditClaimDto editClaimDto = (EditClaimDto) o;
    return Objects.equals(this.oldClaimType, editClaimDto.oldClaimType) &&
        Objects.equals(this.oldClaimValue, editClaimDto.oldClaimValue) &&
        Objects.equals(this.newClaimType, editClaimDto.newClaimType) &&
        Objects.equals(this.newClaimValue, editClaimDto.newClaimValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oldClaimType, oldClaimValue, newClaimType, newClaimValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditClaimDto {\n");
    
    sb.append("    oldClaimType: ").append(toIndentedString(oldClaimType)).append("\n");
    sb.append("    oldClaimValue: ").append(toIndentedString(oldClaimValue)).append("\n");
    sb.append("    newClaimType: ").append(toIndentedString(newClaimType)).append("\n");
    sb.append("    newClaimValue: ").append(toIndentedString(newClaimValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

