/*
 * IdentityExpress Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nanthealth.identityexpress.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nanthealth.identityexpress.api.client.model.ClaimDto;
import com.nanthealth.identityexpress.api.client.model.RoleDto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * UserDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-24T03:48:05.487Z")
public class UserDto {
  @SerializedName("subject")
  private String subject = null;

  @SerializedName("username")
  private String username = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("firstName")
  private String firstName = null;

  @SerializedName("lastName")
  private String lastName = null;

  @SerializedName("isBlocked")
  private Boolean isBlocked = null;

  @SerializedName("lockoutEnd")
  private OffsetDateTime lockoutEnd = null;

  @SerializedName("lockoutEnabled")
  private Boolean lockoutEnabled = null;

  @SerializedName("isDeleted")
  private Boolean isDeleted = null;

  @SerializedName("roles")
  private List<RoleDto> roles = null;

  @SerializedName("claims")
  private List<ClaimDto> claims = null;

  public UserDto subject(String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * Get subject
   * @return subject
  **/
  @ApiModelProperty(value = "")
  public String getSubject() {
    return subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }

  public UserDto username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public UserDto email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UserDto firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public UserDto lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public UserDto isBlocked(Boolean isBlocked) {
    this.isBlocked = isBlocked;
    return this;
  }

   /**
   * Get isBlocked
   * @return isBlocked
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsBlocked() {
    return isBlocked;
  }

  public void setIsBlocked(Boolean isBlocked) {
    this.isBlocked = isBlocked;
  }

  public UserDto lockoutEnd(OffsetDateTime lockoutEnd) {
    this.lockoutEnd = lockoutEnd;
    return this;
  }

   /**
   * Get lockoutEnd
   * @return lockoutEnd
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getLockoutEnd() {
    return lockoutEnd;
  }

  public void setLockoutEnd(OffsetDateTime lockoutEnd) {
    this.lockoutEnd = lockoutEnd;
  }

  public UserDto lockoutEnabled(Boolean lockoutEnabled) {
    this.lockoutEnabled = lockoutEnabled;
    return this;
  }

   /**
   * Get lockoutEnabled
   * @return lockoutEnabled
  **/
  @ApiModelProperty(value = "")
  public Boolean isLockoutEnabled() {
    return lockoutEnabled;
  }

  public void setLockoutEnabled(Boolean lockoutEnabled) {
    this.lockoutEnabled = lockoutEnabled;
  }

  public UserDto isDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
    return this;
  }

   /**
   * Get isDeleted
   * @return isDeleted
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsDeleted() {
    return isDeleted;
  }

  public void setIsDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }

  public UserDto roles(List<RoleDto> roles) {
    this.roles = roles;
    return this;
  }

  public UserDto addRolesItem(RoleDto rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<RoleDto>();
    }
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @ApiModelProperty(value = "")
  public List<RoleDto> getRoles() {
    return roles;
  }

  public void setRoles(List<RoleDto> roles) {
    this.roles = roles;
  }

  public UserDto claims(List<ClaimDto> claims) {
    this.claims = claims;
    return this;
  }

  public UserDto addClaimsItem(ClaimDto claimsItem) {
    if (this.claims == null) {
      this.claims = new ArrayList<ClaimDto>();
    }
    this.claims.add(claimsItem);
    return this;
  }

   /**
   * Get claims
   * @return claims
  **/
  @ApiModelProperty(value = "")
  public List<ClaimDto> getClaims() {
    return claims;
  }

  public void setClaims(List<ClaimDto> claims) {
    this.claims = claims;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserDto userDto = (UserDto) o;
    return Objects.equals(this.subject, userDto.subject) &&
        Objects.equals(this.username, userDto.username) &&
        Objects.equals(this.email, userDto.email) &&
        Objects.equals(this.firstName, userDto.firstName) &&
        Objects.equals(this.lastName, userDto.lastName) &&
        Objects.equals(this.isBlocked, userDto.isBlocked) &&
        Objects.equals(this.lockoutEnd, userDto.lockoutEnd) &&
        Objects.equals(this.lockoutEnabled, userDto.lockoutEnabled) &&
        Objects.equals(this.isDeleted, userDto.isDeleted) &&
        Objects.equals(this.roles, userDto.roles) &&
        Objects.equals(this.claims, userDto.claims);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subject, username, email, firstName, lastName, isBlocked, lockoutEnd, lockoutEnabled, isDeleted, roles, claims);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserDto {\n");
    
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    isBlocked: ").append(toIndentedString(isBlocked)).append("\n");
    sb.append("    lockoutEnd: ").append(toIndentedString(lockoutEnd)).append("\n");
    sb.append("    lockoutEnabled: ").append(toIndentedString(lockoutEnabled)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    claims: ").append(toIndentedString(claims)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

